import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Majbul Rahman
 */
public class home extends javax.swing.JFrame {
           public int z=0;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        NewBuyer.setVisible(false);
        UpdateBuyer.setVisible(false);
        BuyerDetails.setVisible(false);
        DeleteBuyer.setVisible(false);
        NewProduct.setVisible(false);
        UpdateProduct.setVisible(false);
        ProductDetails.setVisible(false);
        DeleteProduct.setVisible(false);
        Billing.setVisible(false);
        Logout.setVisible(false);
        close.setVisible(false);
        NewB.setVisible(false);
        UpdateB.setVisible(false);
        BuyerD.setVisible(false);
        DeleteB.setVisible(false);
        NewP.setVisible(false);
        UpdateP.setVisible(false);
        ProductD.setVisible(false);
        DeleteP.setVisible(false);
        Bill.setVisible(false);
        LogO.setVisible(false);
        Close.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Control = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        NewBuyer = new javax.swing.JButton();
        NewB = new javax.swing.JLabel();
        UpdateBuyer = new javax.swing.JButton();
        UpdateB = new javax.swing.JLabel();
        BuyerDetails = new javax.swing.JButton();
        DeleteP = new javax.swing.JLabel();
        DeleteBuyer = new javax.swing.JButton();
        BuyerD = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        NewProduct = new javax.swing.JButton();
        NewP = new javax.swing.JLabel();
        ProductDetails = new javax.swing.JButton();
        ProductD = new javax.swing.JLabel();
        UpdateProduct = new javax.swing.JButton();
        UpdateP = new javax.swing.JLabel();
        DeleteProduct = new javax.swing.JButton();
        DeleteB = new javax.swing.JLabel();
        Billing = new javax.swing.JButton();
        Bill = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        LogO = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        Control.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hide and show 2.png"))); // NOI18N
        Control.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ControlMouseClicked(evt);
            }
        });
        Control.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(153, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("HOME PAGES");

        jSeparator2.setForeground(new java.awt.Color(153, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NewBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new buyersss.png"))); // NOI18N
        NewBuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                NewBuyerComponentShown(evt);
            }
        });
        NewBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerActionPerformed(evt);
            }
        });

        NewB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NewB.setText("   New Buyers");

        UpdateBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateee.png"))); // NOI18N
        UpdateBuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateBuyerComponentShown(evt);
            }
        });
        UpdateBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyerActionPerformed(evt);
            }
        });

        UpdateB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateB.setText("  Update Buyers");

        BuyerDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyers detailsss.png"))); // NOI18N
        BuyerDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BuyerDetailsComponentShown(evt);
            }
        });
        BuyerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyerDetailsActionPerformed(evt);
            }
        });

        DeleteP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteP.setText("Delete Products");

        DeleteBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete buyersss.png"))); // NOI18N
        DeleteBuyer.setText(" ");
        DeleteBuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteBuyerComponentShown(evt);
            }
        });
        DeleteBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBuyerActionPerformed(evt);
            }
        });

        BuyerD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BuyerD.setText(" Buyers Details");

        Logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logouttt.png"))); // NOI18N
        Logout.setText("LOG-OUT");
        Logout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                LogoutComponentShown(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(153, 0, 51));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new producttt.png"))); // NOI18N
        NewProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                NewProductComponentShown(evt);
            }
        });
        NewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProductActionPerformed(evt);
            }
        });

        NewP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NewP.setText("  New Products");

        ProductDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/product Detaills.png"))); // NOI18N
        ProductDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ProductDetailsComponentShown(evt);
            }
        });
        ProductDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductDetailsActionPerformed(evt);
            }
        });

        ProductD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ProductD.setText("Product Details");

        UpdateProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update productss.png"))); // NOI18N
        UpdateProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateProductComponentShown(evt);
            }
        });
        UpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProductActionPerformed(evt);
            }
        });

        UpdateP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateP.setText("Update Product");

        DeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete producttt.png"))); // NOI18N
        DeleteProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteProductComponentShown(evt);
            }
        });
        DeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductActionPerformed(evt);
            }
        });

        DeleteB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteB.setText("Delete Buyers");

        Billing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billinggg.png"))); // NOI18N
        Billing.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BillingComponentShown(evt);
            }
        });
        Billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingActionPerformed(evt);
            }
        });

        Bill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bill.setText("        Billing");

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/closeee.png"))); // NOI18N
        close.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                closeComponentShown(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        LogO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogO.setText("LogOut");

        Close.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Close.setText("      Close");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(Control, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Billing, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(228, 228, 228))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(DeleteP, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NewP))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ProductD, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ProductDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UpdateP)
                                            .addComponent(UpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NewBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NewB))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(BuyerD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(BuyerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UpdateBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(UpdateB))
                                        .addGap(36, 36, 36)))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeleteBuyer)
                                    .addComponent(DeleteB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Logout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(close))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(LogO, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Control, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewBuyer)
                            .addComponent(UpdateBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuyerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteBuyer, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuyerD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(UpdateProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(DeleteProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ProductDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateP, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(Billing, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogO, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 770));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 820, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerActionPerformed
        // TODO add your handling code here:
         new NewBuy().setVisible(true);
        
    }//GEN-LAST:event_NewBuyerActionPerformed

    private void BuyerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyerDetailsActionPerformed
        // TODO add your handling code here:
        new buyersDetails().setVisible(true);
    }//GEN-LAST:event_BuyerDetailsActionPerformed

    private void UpdateBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyerActionPerformed
        // TODO add your handling code here:
        new UpdateBuyer().setVisible(true);
    }//GEN-LAST:event_UpdateBuyerActionPerformed

    private void DeleteBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBuyerActionPerformed
        // TODO add your handling code here:
        new DeleteBuyer().setVisible(true);
    }//GEN-LAST:event_DeleteBuyerActionPerformed

    private void NewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProductActionPerformed
        // TODO add your handling code here:
          new NewProduct().setVisible(true);
    }//GEN-LAST:event_NewProductActionPerformed

    private void ProductDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductDetailsActionPerformed
        // TODO add your handling code here:
        new ProductDetails().setVisible(true);
         
    }//GEN-LAST:event_ProductDetailsActionPerformed

    private void UpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProductActionPerformed
        // TODO add your handling code here:
          new UpdateProduct().setVisible(true);
    }//GEN-LAST:event_UpdateProductActionPerformed

    private void DeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductActionPerformed
        // TODO add your handling code here:
        new DeleteProduct().setVisible(true);
    }//GEN-LAST:event_DeleteProductActionPerformed

    private void BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingActionPerformed
        // TODO add your handling code here:
         new Billing().setVisible(true);
    }//GEN-LAST:event_BillingActionPerformed

    private void ControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ControlActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(null,"DO you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new login().setVisible(true);
          
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(null,"DO you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
         System.exit(0);
        }
    }//GEN-LAST:event_closeActionPerformed

    private void ControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ControlMouseClicked
        // TODO add your handling code here:
         if(z==0)
        {
            try{
            Thread.sleep(250);
            NewBuyer.setVisible(true);
            NewB.setVisible(true);
            
            }
            catch(Exception e)
            {}
        }
        else
        {
              NewBuyer.setVisible(false);
        UpdateBuyer.setVisible(false);
        BuyerDetails.setVisible(false);
        DeleteBuyer.setVisible(false);
        NewProduct.setVisible(false);
        UpdateProduct.setVisible(false);
        ProductDetails.setVisible(false);
        DeleteProduct.setVisible(false);
        Billing.setVisible(false);
        Logout.setVisible(false);
        close.setVisible(false);
        NewB.setVisible(false);
        UpdateB.setVisible(false);
        BuyerD.setVisible(false);
        DeleteB.setVisible(false);
        NewP.setVisible(false);
        UpdateP.setVisible(false);
        ProductD.setVisible(false);
        DeleteP.setVisible(false);
        Bill.setVisible(false);
        LogO.setVisible(false);
        Close.setVisible(false);
        z=0;
        }
    }//GEN-LAST:event_ControlMouseClicked

    private void NewBuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_NewBuyerComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            BuyerDetails.setVisible(true);
            BuyerD.setVisible(true);
            }
            catch(Exception e)
            {}
         
    }//GEN-LAST:event_NewBuyerComponentShown

    private void BuyerDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BuyerDetailsComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            UpdateBuyer.setVisible(true);
            UpdateB.setVisible(true);  
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_BuyerDetailsComponentShown

    private void UpdateBuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateBuyerComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            DeleteBuyer.setVisible(true);
            DeleteB.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_UpdateBuyerComponentShown

    private void DeleteBuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteBuyerComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            NewProduct.setVisible(true);
            NewP.setVisible(true); 
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_DeleteBuyerComponentShown

    private void NewProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_NewProductComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            ProductDetails.setVisible(true);
            ProductD.setVisible(true);
            }
            catch(Exception e)
            {}
        
    }//GEN-LAST:event_NewProductComponentShown

    private void ProductDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProductDetailsComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            UpdateProduct.setVisible(true);
            UpdateP.setVisible(true);  
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_ProductDetailsComponentShown

    private void UpdateProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateProductComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            DeleteProduct.setVisible(true);
            DeleteP.setVisible(true); 
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_UpdateProductComponentShown

    private void DeleteProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteProductComponentShown
        // TODO add your handling code here:
          try{
            Thread.sleep(250);
            Billing.setVisible(true);
            Bill.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_DeleteProductComponentShown

    private void BillingComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BillingComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            Logout.setVisible(true);
            LogO.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_BillingComponentShown

    private void LogoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LogoutComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            close.setVisible(true);
            Close.setVisible(true);
            z=1;
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_LogoutComponentShown

    private void closeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_closeComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_closeComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bill;
    private javax.swing.JButton Billing;
    private javax.swing.JLabel BuyerD;
    private javax.swing.JButton BuyerDetails;
    private javax.swing.JLabel Close;
    private javax.swing.JButton Control;
    private javax.swing.JLabel DeleteB;
    private javax.swing.JButton DeleteBuyer;
    private javax.swing.JLabel DeleteP;
    private javax.swing.JButton DeleteProduct;
    private javax.swing.JLabel LogO;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel NewB;
    private javax.swing.JButton NewBuyer;
    private javax.swing.JLabel NewP;
    private javax.swing.JButton NewProduct;
    private javax.swing.JLabel ProductD;
    private javax.swing.JButton ProductDetails;
    private javax.swing.JLabel UpdateB;
    private javax.swing.JButton UpdateBuyer;
    private javax.swing.JLabel UpdateP;
    private javax.swing.JButton UpdateProduct;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
