
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Majbul Rahman
 */
public class Homee extends javax.swing.JFrame {
    public int z=0;

    /**
     * Creates new form Homee
     */
    public Homee() {
        initComponents();
        //control.setVisible(false);
        NewBuyer.setVisible(false);
        UpdateBuyer.setVisible(false);
        BuyerDetails.setVisible(false);
        DeleteBuyer.setVisible(false);
        NewProduct.setVisible(false);
        UpdateProduct.setVisible(false);
        ProductDetails.setVisible(false);
        DeleteProduct.setVisible(false);
        Billing.setVisible(false);
        Logout.setVisible(false);
        Close.setVisible(false);
        NewB.setVisible(false);
        UpdateB.setVisible(false);
        BuyerD.setVisible(false);
        DeleteB.setVisible(false);
        NewP.setVisible(false);
        UpdateP.setVisible(false);
        DeleteP.setVisible(false);
        Bill.setVisible(false);
        LogO.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        control = new javax.swing.JButton();
        NewBuyer = new javax.swing.JButton();
        UpdateBuyer = new javax.swing.JButton();
        BuyerDetails = new javax.swing.JButton();
        NewB = new javax.swing.JLabel();
        UpdateB = new javax.swing.JLabel();
        DeleteB = new javax.swing.JLabel();
        DeleteBuyer = new javax.swing.JButton();
        NewProduct = new javax.swing.JButton();
        BuyerD = new javax.swing.JLabel();
        UpdateP = new javax.swing.JLabel();
        UpdateProduct = new javax.swing.JButton();
        NewP = new javax.swing.JLabel();
        ProductDetails = new javax.swing.JButton();
        DeleteProduct = new javax.swing.JButton();
        LogO = new javax.swing.JLabel();
        Billing = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        DeleteP = new javax.swing.JLabel();
        Bill = new javax.swing.JLabel();
        Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        control.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Control hide and show.png"))); // NOI18N
        control.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                controlMouseClicked(evt);
            }
        });
        jPanel1.add(control, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 60, 134, -1));

        NewBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Buyer.png"))); // NOI18N
        NewBuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                NewBuyerComponentShown(evt);
            }
        });
        NewBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerActionPerformed(evt);
            }
        });
        jPanel1.add(NewBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 60, 137, -1));

        UpdateBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update buyer.png"))); // NOI18N
        UpdateBuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateBuyerComponentShown(evt);
            }
        });
        UpdateBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyerActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 60, 134, -1));

        BuyerDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buyer details.png"))); // NOI18N
        BuyerDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BuyerDetailsComponentShown(evt);
            }
        });
        BuyerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyerDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(BuyerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 60, 127, -1));

        NewB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NewB.setForeground(new java.awt.Color(153, 0, 0));
        NewB.setText("           New Buyer");
        jPanel1.add(NewB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 129, 30));

        UpdateB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateB.setForeground(new java.awt.Color(153, 0, 0));
        UpdateB.setText("    Update Buyer");
        jPanel1.add(UpdateB, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 208, 124, 30));

        DeleteB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteB.setForeground(new java.awt.Color(153, 0, 0));
        DeleteB.setText("      Delete Buyer");
        jPanel1.add(DeleteB, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 208, 125, 30));

        DeleteBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete buyer.png"))); // NOI18N
        DeleteBuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteBuyerComponentShown(evt);
            }
        });
        DeleteBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBuyerActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 60, 127, -1));

        NewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new product.png"))); // NOI18N
        NewProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                NewProductComponentShown(evt);
            }
        });
        NewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProductActionPerformed(evt);
            }
        });
        jPanel1.add(NewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 60, 138, -1));

        BuyerD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BuyerD.setForeground(new java.awt.Color(153, 0, 0));
        BuyerD.setText("       Buyer Details");
        jPanel1.add(BuyerD, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 208, 127, 30));

        UpdateP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateP.setForeground(new java.awt.Color(153, 0, 0));
        UpdateP.setText("    Update Product");
        jPanel1.add(UpdateP, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 208, 124, 30));

        UpdateProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update productt.png"))); // NOI18N
        UpdateProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateProductComponentShown(evt);
            }
        });
        UpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProductActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 60, 124, 140));

        NewP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NewP.setForeground(new java.awt.Color(153, 0, 0));
        NewP.setText("       New Product");
        jPanel1.add(NewP, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 208, 124, 30));

        ProductDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ProductDetails.setForeground(new java.awt.Color(153, 0, 0));
        ProductDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productt.png"))); // NOI18N
        ProductDetails.setText("PRODUCT DETAILS");
        ProductDetails.setToolTipText("");
        ProductDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(ProductDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 45));

        DeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete Product.png"))); // NOI18N
        DeleteProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteProductComponentShown(evt);
            }
        });
        DeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(973, 60, 132, -1));

        LogO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogO.setForeground(new java.awt.Color(153, 0, 0));
        LogO.setText("         Logout");
        jPanel1.add(LogO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1249, 208, 121, 30));

        Billing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing.png"))); // NOI18N
        Billing.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BillingComponentShown(evt);
            }
        });
        Billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingActionPerformed(evt);
            }
        });
        jPanel1.add(Billing, new org.netbeans.lib.awtextra.AbsoluteConstraints(1111, 60, 128, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout.png"))); // NOI18N
        Logout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                LogoutComponentShown(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1249, 60, 121, -1));

        DeleteP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteP.setForeground(new java.awt.Color(153, 0, 0));
        DeleteP.setText("    Delete Product");
        jPanel1.add(DeleteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 110, 30));

        Bill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bill.setForeground(new java.awt.Color(153, 0, 0));
        Bill.setText("            Billing");
        jPanel1.add(Bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1111, 208, 128, 30));

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        jPanel1.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1305, 0, -1, 49));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NewBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerActionPerformed
        // TODO add your handling code here:
        new NewBuy().setVisible(true);
    }//GEN-LAST:event_NewBuyerActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"DO you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new login().setVisible(true);
          
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
            int a=JOptionPane.showConfirmDialog(null,"DO you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
         System.exit(0);
        }
    }//GEN-LAST:event_CloseActionPerformed

    private void controlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlMouseClicked
        // TODO add your handling code here:
        if(z==0)
        {
            try{
            Thread.sleep(250);
            NewBuyer.setVisible(true);
            NewB.setVisible(true);
            
            }
            catch(Exception e)
            {}
        }
        else
        {
        NewBuyer.setVisible(false);
        UpdateBuyer.setVisible(false);
        BuyerDetails.setVisible(false);
        DeleteBuyer.setVisible(false);
        NewProduct.setVisible(false);
        UpdateProduct.setVisible(false);
        ProductDetails.setVisible(false);
        DeleteProduct.setVisible(false);
        Billing.setVisible(false);
        Logout.setVisible(false);
        Close.setVisible(false);
        NewB.setVisible(false);
        UpdateB.setVisible(false);
        BuyerD.setVisible(false);
        DeleteB.setVisible(false);
        NewP.setVisible(false);
        UpdateP.setVisible(false);
        DeleteP.setVisible(false);
        Bill.setVisible(false);
        LogO.setVisible(false);
        z=0;
        }
    }//GEN-LAST:event_controlMouseClicked

    private void NewBuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_NewBuyerComponentShown
        // TODO add your handling code here:
           try{
            Thread.sleep(250);
            UpdateBuyer.setVisible(true);
            UpdateB.setVisible(true);
            
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_NewBuyerComponentShown

    private void UpdateBuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateBuyerComponentShown
        // TODO add your handling code here:
           try{
            Thread.sleep(250);
            BuyerDetails.setVisible(true);
            BuyerD.setVisible(true);
            
            }
            catch(Exception e)
            {}
         
    }//GEN-LAST:event_UpdateBuyerComponentShown

    private void BuyerDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BuyerDetailsComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            DeleteBuyer.setVisible(true);
            DeleteB.setVisible(true);
            
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_BuyerDetailsComponentShown

    private void DeleteBuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteBuyerComponentShown
        // TODO add your handling code here:
          try{
            Thread.sleep(250);
            NewProduct.setVisible(true);
            NewP.setVisible(true);
            
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_DeleteBuyerComponentShown

    private void NewProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_NewProductComponentShown
        // TODO add your handling code here:
          try{
            Thread.sleep(250);
            UpdateProduct.setVisible(true);
            UpdateP.setVisible(true);
            
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_NewProductComponentShown

    private void DeleteProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteProductComponentShown
        // TODO add your handling code here:
          try{
            Thread.sleep(250);
            Billing.setVisible(true);
            Bill.setVisible(true);
            
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_DeleteProductComponentShown

    private void BillingComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BillingComponentShown
        // TODO add your handling code here:
          try{
            Thread.sleep(250);
            Logout.setVisible(true);
            LogO.setVisible(true);
            
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_BillingComponentShown

    private void LogoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LogoutComponentShown
        // TODO add your handling code here:
          try{
            Thread.sleep(250);
            ProductDetails.setVisible(true);
            Close.setVisible(true);
            z=1;
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_LogoutComponentShown

    private void UpdateBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyerActionPerformed
        // TODO add your handling code here:
        new UpdateBuyer().setVisible(true);
    }//GEN-LAST:event_UpdateBuyerActionPerformed

    private void BuyerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyerDetailsActionPerformed
        // TODO add your handling code here:
        new buyersDetails().setVisible(true);
    }//GEN-LAST:event_BuyerDetailsActionPerformed

    private void DeleteBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBuyerActionPerformed
        // TODO add your handling code here:
         new DeleteBuyer().setVisible(true);
    }//GEN-LAST:event_DeleteBuyerActionPerformed

    private void NewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProductActionPerformed
        // TODO add your handling code here:
        new NewProduct().setVisible(true);
    }//GEN-LAST:event_NewProductActionPerformed

    private void UpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProductActionPerformed
        // TODO add your handling code here:
        new UpdateProduct().setVisible(true);
    }//GEN-LAST:event_UpdateProductActionPerformed

    private void UpdateProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateProductComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            DeleteProduct.setVisible(true);
            DeleteP.setVisible(true);

        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_UpdateProductComponentShown

    private void ProductDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductDetailsActionPerformed
        // TODO add your handling code here:
        new ProductDetails().setVisible(true);
    }//GEN-LAST:event_ProductDetailsActionPerformed

    private void DeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductActionPerformed
        // TODO add your handling code here:
        new DeleteProduct().setVisible(true);
    }//GEN-LAST:event_DeleteProductActionPerformed

    private void BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingActionPerformed
       new Billing().setVisible(true);
    }//GEN-LAST:event_BillingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bill;
    private javax.swing.JButton Billing;
    private javax.swing.JLabel BuyerD;
    private javax.swing.JButton BuyerDetails;
    private javax.swing.JButton Close;
    private javax.swing.JLabel DeleteB;
    private javax.swing.JButton DeleteBuyer;
    private javax.swing.JLabel DeleteP;
    private javax.swing.JButton DeleteProduct;
    private javax.swing.JLabel LogO;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel NewB;
    private javax.swing.JButton NewBuyer;
    private javax.swing.JLabel NewP;
    private javax.swing.JButton NewProduct;
    private javax.swing.JButton ProductDetails;
    private javax.swing.JLabel UpdateB;
    private javax.swing.JButton UpdateBuyer;
    private javax.swing.JLabel UpdateP;
    private javax.swing.JButton UpdateProduct;
    private javax.swing.JButton control;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
